rootProject.name = "cloud-computer-control"
include("user-service")
include("user-servie-grpc")
include("chat-service")
include("chat-service-grpc")
include("gateway")
include("chat-computer-integration-service")
include("chat-computer-integration-service-grpc")
include("computer-service")
include("computer-service-grpc")
include("connection-service")
include("connection-service-grpc")
include("command-executor-service")
include("command-executor-service-grpc")
include("comman-typing-ai-grpc")
include("text-typing-grpc")
include("telegram-bot")
