# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11userService.proto\"~\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x10\n\x08lastName\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x17\n\x0f\x63onfirmPassword\x18\x06 \x01(\t\"3\n\x10LoginUserRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"]\n\x0cResponseUser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\r\n\x05login\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t2q\n\x0bUserService\x12\x31\n\ncreateUser\x12\x12.CreateUserRequest\x1a\r.ResponseUser\"\x00\x12/\n\tloginUser\x12\x11.LoginUserRequest\x1a\r.ResponseUser\"\x00\x42\x31\n\x1bru.idea.ccc.userservicegrpcB\x10UserServiceProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033ru.idea.ccc.userservicegrpcB\020UserServiceProtoP\001'
  _CREATEUSERREQUEST._serialized_start=21
  _CREATEUSERREQUEST._serialized_end=147
  _LOGINUSERREQUEST._serialized_start=149
  _LOGINUSERREQUEST._serialized_end=200
  _RESPONSEUSER._serialized_start=202
  _RESPONSEUSER._serialized_end=295
  _USERSERVICE._serialized_start=297
  _USERSERVICE._serialized_end=410
# @@protoc_insertion_point(module_scope)
