# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import userService_pb2 as userService__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createUser = channel.unary_unary(
                '/UserService/createUser',
                request_serializer=userService__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=userService__pb2.ResponseUser.FromString,
                )
        self.loginUser = channel.unary_unary(
                '/UserService/loginUser',
                request_serializer=userService__pb2.LoginUserRequest.SerializeToString,
                response_deserializer=userService__pb2.ResponseUser.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createUser': grpc.unary_unary_rpc_method_handler(
                    servicer.createUser,
                    request_deserializer=userService__pb2.CreateUserRequest.FromString,
                    response_serializer=userService__pb2.ResponseUser.SerializeToString,
            ),
            'loginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.loginUser,
                    request_deserializer=userService__pb2.LoginUserRequest.FromString,
                    response_serializer=userService__pb2.ResponseUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserService/createUser',
            userService__pb2.CreateUserRequest.SerializeToString,
            userService__pb2.ResponseUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def loginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserService/loginUser',
            userService__pb2.LoginUserRequest.SerializeToString,
            userService__pb2.ResponseUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
